# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:

#  test_py27:
#    working_directory: /tmp/src/rapidtide
#    docker:
#      - image: continuumio/miniconda3
#    steps:
#      - checkout
#      - persist_to_workspace:
#          root: /tmp
#          paths:
#              - src/rapidtide
#      - run:  # will overwrite rapidtide installation each time
#          name: Generate environment
#          command:  |
#            if [[ -e /opt/conda/envs/py27_env ]]; then
#                echo "Restoring environment from cache"
#                source activate py27_env
#            else
#                conda create -n py27_env python=2.7 -yq
#                source activate py27_env
#                pip install -e .[tests,doc]
#            fi
#            python setup.py install --user
#      - run:
#          name: Run Py2.7 tests
#          command: |
#            source activate py27_env
#            py.test --ignore=rapidtide/candidatetests rapidtide

  test_py36:
    working_directory: /tmp/src/rapidtide
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/rapidtide
      - run:  # will overwrite rapidtide installation each time
          name: Generate environment
          command:  |
            if [[ -e /opt/conda/envs/py36_env ]]; then
                echo "Restoring environment from cache"
                source activate py36_env
            else
                conda create -n py36_env python=3.6 -yq
                source activate py36_env
                pip install -e .[tests,doc]
            fi
            python setup.py install --user
      - run:
          name: Run Py3.6 tests
          command: |
            source activate py36_env
            py.test --ignore=rapidtide/candidatetests rapidtide

  build_py37:
    working_directory: /tmp/src/rapidtide
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/rapidtide
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ checksum "setup.py" }}
      - run:  # will overwrite rapidtide installation each time
          name: Generate environment
          command:  |
            if [[ -e /opt/conda/envs/py37_env ]]; then
                echo "Restoring environment from cache"
                source activate py37_env
            else
                conda create -n py37_env python=3.7 -yq
                source activate py37_env
                pip install -e .[tests,doc]
            fi
            python setup.py install --user
      - save_cache:  # environment cache tied to requirements
          key: deps9-{{ checksum "setup.py" }}
          paths:
            - "/opt/conda/envs/py37_env"

  build_docs:
    working_directory: /tmp/src/rapidtide
    docker:
      - image: continuumio/miniconda3
    steps:
      - attach_workspace:  # get rapidtide
          at: /tmp
      - restore_cache:  # load environment
          key: deps9-{{ checksum "setup.py" }}
      - run:
          name: Build documentation
          command: |
            apt-get install -yqq make
            source activate py37_env
            make -C docs html
      - store_artifacts:
          path: /tmp/src/rapidtide/docs/_build/html

  style_check:
    working_directory: /tmp/src/rapidtide
    docker:
      - image: continuumio/miniconda3
    steps:
      - attach_workspace:  # get rapidtide
          at: /tmp
      - restore_cache:  # load environment
          key: deps9-{{ checksum "setup.py" }}
      - run:
          name: Linting
          command:  |
            source activate py37_env
            flake8 --ignore=E127,E501,E722,E114,E116,W503,W504 /tmp/src/rapidtide/rapidtide
      - store_artifacts:
          path: /tmp/data/lint

  test_py37_with_coverage:
    working_directory: /tmp/src/rapidtide
    docker:
      - image: continuumio/miniconda3
    steps:
      - attach_workspace:  # get rapidtide
          at: /tmp
      - restore_cache:  # load environment
          key: deps9-{{ checksum "setup.py" }}
      - run:
          name: Coverage
          command:  |
            apt-get install -yqq curl
            source activate py37_env
            py.test --ignore=rapidtide/candidatetests --cov-report xml:coverage.xml --cov=rapidtide rapidtide
      - codecov/upload:
          file: /tmp/src/rapidtide/coverage.xml

workflows:
  version: 2.1
  run_tests:
    jobs:
      - test_py36
      - build_py37
      - build_docs:
          requires:
            - build_py37
      - style_check:
          requires:
            - build_py37
      - test_py37_with_coverage:
          requires:
            - build_py37
